### ISSUE TITLE
Ajattelitko tätä projektinhallinta/projektityökurssin repoksi?

### ISSUE THREAD

**Issue by mtijas** [JaniLeht/projekti-paja#1]
Ajattelitko tätä tosiaan tuon projektinhallintakurssin repoksi ryhmällemme, vai tehdäänkö sille oma sitten myöhemmin?

**Comment by JaniLeht** [comment]
tehdään uusi/oikea myöhemmin. Tää oli vaan testaus mitä tehtiin tunnilla

Lähetetty Windows 10:n Sähköposti<https://go.microsoft.com/fwlink/?LinkId=550986>sta

Lähettäjä: Markus Ijäs<mailto:notifications@github.com>
Lähetetty: torstai 10. joulukuuta 2020 13.07
Vastaanottaja: JaniLeht/projekti-paja<mailto:projekti-paja@noreply.github.com>
Kopio: Subscribed<mailto:subscribed@noreply.github.com>
Aihe: [JaniLeht/projekti-paja] Ajattelitko tätä projektinhallinta/projektityökurssin repoksi? (#1)


Ajattelitko tätä tosiaan tuon projektinhallintakurssin repoksi ryhmällemme, vai tehdäänkö sille oma sitten myöhemmin?

**Comment by mtijas** [comment]
Hyvä, näin tehdään.
